ALTER TABLE C_Order DROP CONSTRAINT COrderORDEREDBY_ID
ALTER TABLE ORDERLINE DROP CONSTRAINT ORDERLINE_ITEM_ID
ALTER TABLE CUSTOMER_EMAIL DROP CONSTRAINT CSTOMEREMAILmilsID
ALTER TABLE CUSTOMER_EMAIL DROP CONSTRAINT CSTMREMAILCstmerID
ALTER TABLE C_Order_ORDERLINE DROP CONSTRAINT CrdrORDERLINEtmsID
ALTER TABLE C_Order_ORDERLINE DROP CONSTRAINT CrdrORDERLINErdrID
ALTER TABLE C_Order_NOTIFICATION DROP CONSTRAINT CrdrNTFICATIONrdrD
ALTER TABLE C_Order_NOTIFICATION DROP CONSTRAINT CrdrNTFCTNNtfctnsD
ALTER TABLE C_Order_SHIPMENTLOG DROP CONSTRAINT CrdrSHPMENTLOGrdrD
ALTER TABLE C_Order_SHIPMENTLOG DROP CONSTRAINT CrdrSHPMNShpmntLgD
ALTER TABLE TRUCK_C_Order DROP CONSTRAINT TRUCKCOrderrdersID
ALTER TABLE TRUCK_C_Order DROP CONSTRAINT TRUCKCOrderTruckID
DROP TABLE CUSTOMER
DROP TABLE PRODUCT
DROP TABLE C_Order
DROP TABLE ORDERLINE
DROP TABLE SHIPMENTLOG
DROP TABLE EMAIL
DROP TABLE NOTIFICATION
DROP TABLE TRUCK
DROP TABLE CUSTOMER_EMAIL
DROP TABLE C_Order_ORDERLINE
DROP TABLE C_Order_NOTIFICATION
DROP TABLE C_Order_SHIPMENTLOG
DROP TABLE TRUCK_C_Order
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
